# LAB-7

### *Using Backpropagation Algorithm to Implement OR Gate*

In [1]:
# importing libraries
import numpy as np

In [2]:
# defining input features
X = np.array([[0,0],[0,1],[1,0],[1,1]])  # 4 datapoints
print(X)

[[0 0]
 [0 1]
 [1 0]
 [1 1]]


In [3]:
# defining target outputs
Y_target = np.array([[0],[1],[1],[1]])  # 4 outputs
print(Y_target)

[[0]
 [1]
 [1]
 [1]]


In [4]:
# assigning random weights
# 6 for hidden layer (with 3 neurons)
# 3 for output layer (with 1 neuron)
W1 = np.array([[0.1,0.2,0.3],[0.4,0.5,0.6]])
W2 = np.array([[0.7],[0.8],[0.9]])
print(W1)
print(W2)

# learning rate
lr = 0.05

[[0.1 0.2 0.3]
 [0.4 0.5 0.6]]
[[0.7]
 [0.8]
 [0.9]]


In [5]:
# defining activation function - Sigmoid function
def sigmoid(x):
    return 1/(1+np.exp(-x))

In [6]:
# defining derivative of activation function - derivative of the Sigmoid function
def der_sigmoid(x):
    return sigmoid(x)*(1-sigmoid(x))

### Forward Propagation (first iteration)

In [7]:
Z = np.dot(X,W1)  # pre-activation matrix for the neurons in hidden layer
print('Z:\n',Z)
H = sigmoid(Z)    # post-activation matrix 
print('\nH:\n',H)
U = np.dot(H,W2)  # pre-activation matrix for the neuron in output layer
print('\nU:\n',U)
Y = sigmoid(U)    # post-activation matrix
print('\nY:\n',Y)
E = Y-Y_target    # the error due to selection of random weights
print('\nE:\n',E)

Z:
 [[0.  0.  0. ]
 [0.4 0.5 0.6]
 [0.1 0.2 0.3]
 [0.5 0.7 0.9]]

H:
 [[0.5        0.5        0.5       ]
 [0.59868766 0.62245933 0.64565631]
 [0.52497919 0.549834   0.57444252]
 [0.62245933 0.66818777 0.7109495 ]]

U:
 [[1.2       ]
 [1.4981395 ]
 [1.32435089]
 [1.6101263 ]]

Y:
 [[0.76852478]
 [0.81729683]
 [0.78990467]
 [0.83342892]]

E:
 [[ 0.76852478]
 [-0.18270317]
 [-0.21009533]
 [-0.16657108]]


### *Error is huge, so we'll have to backpropagate it and repeat the cycle till the results become accurate.*

### The Neural Network

In [8]:
for epoch in range(1000):
    # first, forward propagation will happen
    Z = np.dot(X,W1)  
    H = sigmoid(Z)    
    U = np.dot(H,W2) 
    Y = sigmoid(U)    
    E = Y-Y_target    
    
    # calculation of loss function (Mean Square Error loss)
    L = 1/2*(np.power(E,2))
    #print(output_error.sum())
    #print(output_error)

    # Backpropagation - Stage 1
    dL_dY = Y-Y_target
    dY_dU = Y*(1-Y)
    dU_dW2 = H
    #print(dL_dY)
    #print(dY_dU)
    #print(dU_dW2)

    dL_dW2=np.dot(dU_dW2.T,dL_dY*dY_dU)

    # weight updates in stage 1
    W2 -= lr*dL_dW2
    #print(weight_output)

    # Backpropagation - Stage 2
    dL_dY = Y-Y_target
    dY_dU = Y*(1-Y)
    dU_dH = W2
    dH_dZ = H*(1-H)
    dZ_dW1 = X 

    dL_dH = np.dot(dL_dY*dY_dU,dU_dH.T)
    dL_dW1 = np.dot(dZ_dW1.T,dH_dZ*dL_dH)

    # weight updates in stage 2
    W1 -= lr*dL_dW1
    #print(weight_hidden)
    
print(W2)
print(W1)

[[0.32201495]
 [0.62000475]
 [0.89078803]]
[[0.46468764 0.67734655 0.86279697]
 [0.71839648 0.91116206 1.07828517]]


In [9]:
# testing on an input data point
point = np.array([0,0])
z = np.dot(point,W1)
h = sigmoid(z)
op = np.dot(h,W2)
y_cap = sigmoid(op)
print(y_cap)

[0.7143088]
